on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: earlyjester/sftp-trans
        with:
          username: ${{ secrets.SFTPUSER }}
          server: ${{ secrets.SERVERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './*'
          remote_path: '/'
          args: '-o ConnectTimeout=5'